import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { afterEach, expect, it, vi } from 'vitest';
import { GitBackup } from '../lib/git-backup.js';
const dirs: string[] = [];
const git = (dir: string, ...args: string[]) => execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8' }).trim();
afterEach(() => { vi.unstubAllEnvs(); for (const d of dirs.splice(0))
    rmSync(d, { recursive: true, force: true }); });
it.each(['', '   '])('leaves optional backup disabled without reading definitions or creating a checkout (%j)', async remote => {
    const root=mkdtempSync(join(tmpdir(),'keeper-no-backup-'));dirs.push(root);
    const source=vi.fn(async()=>{throw new Error('Disabled backup must not read definitions');});
    const checkout=join(root,'checkout');
    const backup=new GitBackup({checkout,remote:async()=>remote,source});
    await expect(backup.commit('sample','owner@example.com','Saved definition')).resolves.toBe('disabled');
    expect(source).not.toHaveBeenCalled();
    expect(existsSync(checkout)).toBe(false);
});
it('preserves remote history/unrelated files; tracks retired sources and remote advancement without force', async () => {
    const root = mkdtempSync(join(tmpdir(), 'keeper-backup-'));
    dirs.push(root);
    const remote = join(root, 'remote.git'), seed = join(root, 'seed');
    mkdirSync(remote);
    git(remote, 'init', '--bare');
    git(root, 'clone', remote, seed);
    git(seed, 'config', 'user.name', 'Test');
    git(seed, 'config', 'user.email', 'test@example.com');
    writeFileSync(join(seed, 'unrelated'), 'keep');
    git(seed, 'add', '.');
    git(seed, 'commit', '-m', 'seed');
    git(seed, 'push', 'origin', 'HEAD');
    const original = git(seed, 'rev-parse', 'HEAD');
    const active = join(root, 'agents'), retired = join(root, 'retired');
    mkdirSync(active);
    mkdirSync(retired);
    let source = join(active, 'sample');
    mkdirSync(source);
    const contents = { 'agent.json': '{"name":"sample"}', 'duties.md': 'Owner text', 'voice.md': 'Voice' };
    for (const [f, s] of Object.entries(contents))
        writeFileSync(join(source, f), s);
    const backup = new GitBackup({ checkout: join(root, 'checkout'), remote: async () => remote, source: async () => source });
    await backup.commit('sample', 'owner@example.com', 'Saved definition');
    writeFileSync(join(seed, 'other'), 'remote change');
    git(seed, 'pull', '--rebase');
    git(seed, 'add', '.');
    git(seed, 'commit', '-m', 'remote advance');
    git(seed, 'push');
    source = join(retired, 'sample-date-id');
    mkdirSync(source);
    for (const [f, s] of Object.entries(contents))
        writeFileSync(join(source, f), s + ' retired');
    await backup.commit('sample', 'owner@example.com', 'Retired definition');
    git(seed, 'pull', '--ff-only');
    expect(readFileSync(join(seed, 'unrelated'), 'utf8')).toBe('keep');
    expect(readFileSync(join(seed, 'other'), 'utf8')).toBe('remote change');
    expect(readFileSync(join(seed, 'definitions/sample/duties.md'), 'utf8')).toBe('Owner text retired');
    expect(git(seed, 'merge-base', '--is-ancestor', original, 'HEAD')).toBe('');
    expect(git(seed, 'log', '--format=%s')).toContain('Saved definition');
});
it('retains an unpushed commit on rejection and retries without rewriting remote history', async () => {
    const {chmodSync} = await import('node:fs');
    const root=mkdtempSync(join(tmpdir(),'keeper-rejected-backup-'));dirs.push(root);
    const remote=join(root,'remote.git'),seed=join(root,'seed'),source=join(root,'source');
    mkdirSync(remote);git(remote,'init','--bare');git(root,'clone',remote,seed);
    git(seed,'config','user.name','Test');git(seed,'config','user.email','test@example.com');writeFileSync(join(seed,'unrelated'),'keep');git(seed,'add','.');git(seed,'commit','-m','seed');git(seed,'push','origin','HEAD');
    const baseline=git(seed,'rev-parse','HEAD');mkdirSync(source);
    for(const file of ['agent.json','duties.md','voice.md'])writeFileSync(join(source,file),file==='agent.json'?'{}':'text');
    const checkout=join(root,'checkout');const backup=new GitBackup({checkout,remote:async()=>remote,source:async()=>source});
    const hook=join(remote,'hooks/pre-receive');writeFileSync(hook,'#!/bin/sh\nexit 1\n');chmodSync(hook,0o700);
    await expect(backup.commit('sample','owner@example.com','First save')).rejects.toThrow();
    expect(git(remote,'rev-parse','HEAD')).toBe(baseline);expect(git(checkout,'rev-parse','HEAD')).not.toBe(baseline);
    expect(readFileSync(join(source,'duties.md'),'utf8')).toBe('text');rmSync(hook);
    await backup.commit('sample','owner@example.com','Retry save');
    git(seed,'pull','--ff-only');expect(git(seed,'log','--format=%s')).toContain('First save');expect(git(seed,'merge-base','--is-ancestor',baseline,'HEAD')).toBe('');
});

it('rebases a retained rejected save above remote advancement without ambient Git identity', async () => {
    const { chmodSync } = await import('node:fs');
    vi.stubEnv('GIT_CONFIG_NOSYSTEM', '1');
    vi.stubEnv('GIT_CONFIG_SYSTEM', '/dev/null');
    vi.stubEnv('GIT_CONFIG_GLOBAL', '/dev/null');
    vi.stubEnv('GIT_CONFIG_PARAMETERS', '');
    vi.stubEnv('GIT_CONFIG_COUNT', '1');
    vi.stubEnv('GIT_CONFIG_KEY_0', 'user.useConfigOnly');
    vi.stubEnv('GIT_CONFIG_VALUE_0', 'true');
    for (const key of ['GIT_AUTHOR_NAME', 'GIT_AUTHOR_EMAIL', 'GIT_COMMITTER_NAME', 'GIT_COMMITTER_EMAIL', 'EMAIL']) vi.stubEnv(key, undefined);
    const root = mkdtempSync(join(tmpdir(), 'keeper-clean-git-'));
    dirs.push(root);
    const remote = join(root, 'remote.git'), seed = join(root, 'seed'), source = join(root, 'source'), checkout = join(root, 'checkout');
    mkdirSync(remote);
    git(remote, 'init', '--bare');
    git(root, 'clone', remote, seed);
    git(seed, 'config', 'user.name', 'Remote owner');
    git(seed, 'config', 'user.email', 'remote@example.com');
    writeFileSync(join(seed, 'unrelated'), 'original remote text');
    git(seed, 'add', '.');
    git(seed, 'commit', '-m', 'seed');
    git(seed, 'push', 'origin', 'HEAD');
    const baseline = git(seed, 'rev-parse', 'HEAD');
    mkdirSync(source);
    for (const file of ['agent.json', 'duties.md', 'voice.md']) writeFileSync(join(source, file), file === 'agent.json' ? '{}' : 'saved text');
    const backup = new GitBackup({ checkout, remote: async () => remote, source: async () => source });
    const hook = join(remote, 'hooks/pre-receive');
    writeFileSync(hook, '#!/bin/sh\nexit 1\n');
    chmodSync(hook, 0o700);
    await expect(backup.commit('sample', 'original@example.com', 'Retained save')).rejects.toThrow();
    expect(git(remote, 'rev-parse', 'HEAD')).toBe(baseline);
    expect(git(checkout, 'rev-parse', 'HEAD')).not.toBe(baseline);
    expect(() => git(checkout, 'config', '--get', 'user.email')).toThrow();
    rmSync(hook);
    writeFileSync(join(seed, 'unrelated'), 'advanced remote text');
    git(seed, 'add', '.');
    git(seed, 'commit', '-m', 'independent remote advance');
    git(seed, 'push');
    const advanced = git(seed, 'rev-parse', 'HEAD');
    await backup.commit('sample', 'retry@example.com', 'Retry save');
    git(seed, 'pull', '--ff-only');
    expect(git(seed, 'merge-base', '--is-ancestor', advanced, 'HEAD')).toBe('');
    expect(readFileSync(join(seed, 'unrelated'), 'utf8')).toBe('advanced remote text');
    expect(readFileSync(join(seed, 'definitions/sample/duties.md'), 'utf8')).toBe('saved text');
    expect(git(seed, 'log', '--format=%an|%cn|%ce', '--grep=^Retained save:')).toBe('original@example.com|Lares keeper|keeper@localhost');
    expect(git(seed, 'log', '-1', '--format=%an')).toBe('retry@example.com');
    expect(() => git(checkout, 'config', '--get', 'user.email')).toThrow();
});
