import { beforeEach, describe, expect, it, vi } from 'vitest';
const sdk = vi.hoisted(() => ({ init: vi.fn(), capture: vi.fn(), opt_in_capturing: vi.fn(), opt_out_capturing: vi.fn(), reset: vi.fn() }));
vi.mock('posthog-js', () => ({ default: sdk }));
beforeEach(() => { vi.resetModules(); vi.clearAllMocks(); vi.stubEnv('NEXT_PUBLIC_POSTHOG_KEY', 'public-test-token'); vi.stubGlobal('location', { hostname: 'lares.is', origin: 'https://lares.is', pathname: '/docs/console/', search: '?email=private@example.com&utm_source=search' }); vi.stubGlobal('document', { referrer: 'https://example.com/private?token=secret' }); });
describe('marketing analytics privacy boundary', () => {
  it('does not initialize or capture before consent', async () => { const a = await import('../lib/analytics'); a.capture('$pageview'); expect(sdk.init).not.toHaveBeenCalled(); expect(sdk.capture).not.toHaveBeenCalled(); });
  it('does not initialize on local or preview hosts even with consent', async () => { vi.stubGlobal('location', { hostname: 'localhost' }); const a = await import('../lib/analytics'); await a.setAnalyticsConsent(true); a.capture('$pageview'); expect(sdk.init).not.toHaveBeenCalled(); expect(sdk.capture).not.toHaveBeenCalled(); });
  it('initializes only EU analytics with recording and autocapture disabled', async () => { const a = await import('../lib/analytics'); await a.setAnalyticsConsent(true); expect(sdk.init.mock.calls[0][1]).toMatchObject({ api_host: 'https://eu.i.posthog.com', autocapture: false, disable_session_recording: true, capture_pageview: false }); });
  it('stops capturing immediately after withdrawal', async () => { const a = await import('../lib/analytics'); await a.setAnalyticsConsent(true); a.capture('booking_opened'); await a.setAnalyticsConsent(false); a.capture('booking_completed'); expect(sdk.capture).toHaveBeenCalledTimes(1); expect(sdk.opt_out_capturing).toHaveBeenCalled(); });
  it('removes query strings, form fields and unapproved SDK properties', async () => { const { sanitizeProperties } = await import('../lib/analytics'); expect(sanitizeProperties({ '$current_url': 'https://lares.is/docs/?email=secret#token', '$initial_current_url': 'https://lares.is/?secret', email: 'secret', search: 'private query', bookingId: 'private-id', path: '/docs/', action: 'docs' })).toEqual({ '$current_url': 'https://lares.is/docs/', path: '/docs/', action: 'docs' }); });
  it('captures a sanitized page path and referring domain', async () => { const a = await import('../lib/analytics'); await a.setAnalyticsConsent(true); a.pageview(); expect(sdk.capture).toHaveBeenCalledWith('$pageview', expect.objectContaining({ '$current_url': 'https://lares.is/docs/console/', referrer_domain: 'example.com', surface: 'docs', utm_source: 'search' })); expect(JSON.stringify(sdk.capture.mock.calls)).not.toContain('private'); });
  it('drops unknown events and captures no identity profiles', async () => { const a = await import('../lib/analytics'); await a.setAnalyticsConsent(true); a.capture('form_submitted', { email: 'secret' }); expect(sdk.capture).not.toHaveBeenCalled(); expect(sdk.init.mock.calls[0][1].person_profiles).toBe('identified_only'); });
  it('withdrawal wins over an in-flight SDK import', async () => { const a = await import('../lib/analytics'); const pending = a.setAnalyticsConsent(true); await a.setAnalyticsConsent(false); await pending; expect(sdk.init).not.toHaveBeenCalled(); });
});
