#!/bin/sh
# Generated by packages/agent-kit/bin/generate-settings.ts — never hand-edited.
# Refuses to start when a required setting is missing or blank, or when a setting that names
# a secret FILE points at one that cannot be read or has nothing in it. Never echoes a value —
# only the setting's NAME, its already-committed sentence, and for a file the PATH.
set -eu
missing=0
lares_require() { eval "v=\${$1-}"; [ -n "${v#"${v%%[![:space:]]*}"}" ] || { echo "lares: $1 is not set. $2" >&2; missing=1; }; }
lares_require_file() { eval "p=\${$1-}"; [ -n "${p#"${p%%[![:space:]]*}"}" ] || { echo "lares: $1 is not set. $2" >&2; missing=1; return; }; [ -r "$p" ] || { echo "lares: $1 points to a file that does not exist or cannot be read ($p). $2" >&2; missing=1; return; }; [ -s "$p" ] || { echo "lares: $1 points to a file that exists but is empty ($p). $2" >&2; missing=1; }; }
lares_require DATABASE_URL "The role image's own startup guard refuses to start at all, before any request is served."
lares_require WORKFLOW_POSTGRES_URL "The role image's own startup guard refuses to start; eve has nowhere durable to keep a workflow's state."
lares_require_file DATABASE_PASSWORD_FILE "The role image's own startup guard refuses to start; it is also what exports PGPASSWORD, so the database connection has no password."
lares_require GATEWAY_URL "The role image's own startup guard refuses to start; nothing can reach the model gateway to complete a turn."
lares_require_file GATEWAY_KEY_FILE "The role image's own startup guard refuses to start; the gateway would refuse every request as unauthenticated."
lares_require LARES_AGENT_NAME "The role image's own startup guard refuses to start; the agent has no identity to load a definition or a mailbox for."
lares_require LARES_DEFINITION_DIR "The role image's own startup guard refuses to start; there is no definition directory to load agent.json or voice.md from."
[ "$missing" -eq 0 ] || exit 1
