// One list says what every setting the engine reads is for, and what breaks without it.
//
// Written against `.claude/plans/2026-09-20-prelaunch-wave-8.md` (W8A-s1). The plan's own read
// of the code found ~137 names in two layers: ~113 read as a
// literal `process.env.NAME` / `env["NAME"]`, and at least 24 more reached only through a
// helper that takes the name as a string (`readSecret(name)`, `readSecret(`${name}_FILE`)`,
// `keyFromEnv(varName)`, a computed `LARES_${channel}_PRINCIPAL`) or read by something other
// than this repository's TypeScript (a shell script, the `git` binary, the Node runtime's own
// timezone handling). This file declares both layers as one list.
//
// THIS SLICE (W8A-s1) ONLY WRITES THE LIST DOWN. It does not change how any service reads its
// environment, and it does not widen what is fatal to start without — `requiredFor` here is
// exactly the seven names `images/agent-runtime/start.sh` already refuses on, for the three
// role readers, plus `CONSOLE_SESSION_SECRET` (throws in production). `CONSOLE_ALLOWED_EMAILS`
// also throws in production, but the code never merely "starts or doesn't" on it — outside
// production it silently DEGRADES to one installation's own address (contradiction item 5) —
// so it is declared with that fallback and left out of `requiredFor`, matching this file's own
// invariant that a required setting has no fallback. Widening `requiredFor` is a later slice's
// job, done with evidence.
//
// NOT DECLARED (deliberately) — three names that are doc-comment EXAMPLES, never a real
// setting: `X_KEY_FILE` (`packages/agent-kit/src/integration-secret-lint.ts`), and
// `SOME_CLIENT_ID_FILE` / `MY_KEY` (the console's own secrets tests).
//
// OUT OF SCOPE (deliberately) — every name read only inside `packages/board-evals`
// (`SEAM_GRANTS`, `BOARD_LEVELS`, `BOARD_LOG`, `BOARD_SKEW`, `BOARD_EVENTS`, `PROOF_MODEL_LOG`):
// that package IS the eval/probe harness end to end, not a shipped installation surface, which
// is the same reason the plan's own count is over "non-test, non-eval source".
//
// NOT DECLARED (a real gap, not this slice's to close) — `WEEKLY_SUMMARY_HOUR` and
// `ROUTE_HOURS` still appear in `services/keeper/lib/runtime-bindings.ts`'s bindable
// `environmentKeys`, but nothing reads either any more (schedules read their hour from
// `@lares/agent-kit/schedule-settings` instead, per the wave-3 notes) — declaring them would
// give `readAt` a line to point at that lies about who reads it.

/** Which part of an installation reads a setting. A name may be read by several. */
export type SettingReader =
  | "agent-kit"
  | "chief-of-staff"
  | "travel"
  | "creative"
  | "console"
  | "box"
  | "keeper"
  | "atlas"
  | "notion-sync"
  | "readability"
  | "gateway"
  | "caddy";

/** Who is expected to supply the value. */
export type SettingSource =
  | "installer" // the install command writes it and the owner never sees it
  | "owner" // the wizard asks for it
  | "integration" // only set when that integration is switched on
  | "legacy"; // a persona- or installation-named spelling wave 9 removes

export interface SettingDef {
  /** The environment variable name, exactly as the code reads it. */
  readonly name: string;
  readonly readers: readonly SettingReader[];
  readonly source: SettingSource;
  /** Required for the readers listed here to start at all. */
  readonly requiredFor: readonly SettingReader[];
  /** The value used when it is unset, or null when there is none. */
  readonly fallback: string | null;
  /** True when the VALUE is a credential. A `_FILE` name is NOT secret — the path is not. */
  readonly secret: boolean;
  /** One sentence, owner-readable, saying what goes wrong and how loudly. */
  readonly breaksWithout: string;
  /** Where it is read. `file:line` at the time of writing, a hint only. */
  readonly readAt: readonly string[];
}

const ROLES: readonly SettingReader[] = ["chief-of-staff", "travel", "creative"];

/** A probe/dev-only knob: never set on an installation, so it never breaks one. */
const NOT_AN_INSTALLATION_SETTING =
  "Nothing — this is a switch for a hand-run probe, never set on an installation.";

export const SETTINGS: readonly SettingDef[] = [
  {
    name: "LARES_ATLAS_REPOSITORIES_FILE",
    readers: ["atlas"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Repository-source reads fail without an explicit mounted repository mapping.",
    readAt: ["services/atlas/lib/adapters/github-source.ts"],
  },
  {
    name: "LARES_ATLAS_PROBE_CODEBASE",
    readers: ["atlas"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Doctor mode refuses to run until an operator probe codebase is configured.",
    readAt: ["services/atlas/bin/atlas-sync.ts"],
  },
  {
    name: "LARES_ATLAS_PROBE_NOTION_PAGE",
    readers: ["atlas"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Doctor mode refuses to run until an operator probe page is configured.",
    readAt: ["services/atlas/bin/atlas-sync.ts"],
  },
  {
    name: "LARES_HTTP_USER_AGENT",
    readers: ["travel"],
    source: "integration",
    requiredFor: [],
    fallback: "Lares/0.1 (+https://github.com/Heiberg-Industries/lares)",
    secret: false,
    breaksWithout: "Uses the public Lares project identity for weather and geocoding HTTP requests.",
    readAt: ["services/travel/catalogue/weather_forecast.ts"],
  },
  // ── The startup guard — images/agent-runtime/start.sh, required for every role image ──────
  {
    name: "DATABASE_URL",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start at all, before any request is served.",
    readAt: ["images/agent-runtime/start.sh:3", "packages/agent-kit/src/db.ts:20"],
  },
  {
    name: "WORKFLOW_POSTGRES_URL",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start; eve has nowhere durable to keep a workflow's state.",
    readAt: ["images/agent-runtime/start.sh:4", "packages/agent-kit/src/release-stale-workflow-locks.ts:63"],
  },
  {
    name: "DATABASE_PASSWORD_FILE",
    readers: ["chief-of-staff", "travel", "creative", "box"],
    source: "installer",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start; it is also what exports PGPASSWORD, so the database connection has no password.",
    readAt: ["images/agent-runtime/start.sh:5", "images/agent-runtime/start.sh:10", "services/keeper/lib/compose-agents.ts:69"],
  },
  {
    name: "GATEWAY_URL",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative", "atlas"],
    source: "owner",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start; nothing can reach the model gateway to complete a turn.",
    readAt: ["images/agent-runtime/start.sh:6", "packages/agent-kit/src/gateway-provider.ts:74", "services/atlas/lib/config.ts:104"],
  },
  {
    // Added by 8F/F8, NOT by F6 as that slice's plan expected: `tests/settings-scan.test.ts`
    // fails the moment engine code READS an undeclared name, so a slice that introduces a read
    // must declare it in the same change — it cannot be deferred to a later slice.
    name: "GATEWAY_LANE",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative"],
    source: "owner",
    requiredFor: [],
    fallback: "anthropic",
    secret: false,
    breaksWithout:
      "Nothing breaks — GATEWAY_LANE is optional. Unset, every agent uses the anthropic lane (the only lane with production history). Set to \"openai-compatible\" on an agent whose model target is not Anthropic, to route its calls through the gateway's OpenAI-compatible route instead.",
    readAt: ["packages/agent-kit/src/gateway-provider.ts:56"],
  },
  {
    name: "GATEWAY_KEY_FILE",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start; the gateway would refuse every request as unauthenticated.",
    readAt: ["images/agent-runtime/start.sh:7", "images/agent-runtime/start.sh:10", "packages/agent-kit/src/gateway-provider.ts:86", "services/keeper/lib/compose-agents.ts:69"],
  },
  {
    name: "LARES_AGENT_NAME",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start; the agent has no identity to load a definition or a mailbox for.",
    readAt: ["images/agent-runtime/start.sh:8", "services/chief-of-staff/lib/definition.ts:130"],
  },
  {
    name: "LARES_DEFINITION_DIR",
    readers: ["agent-kit", "chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: ROLES,
    fallback: null,
    secret: false,
    breaksWithout: "The role image's own startup guard refuses to start; there is no definition directory to load agent.json or voice.md from.",
    readAt: ["images/agent-runtime/start.sh:9", "packages/agent-kit/src/definition-cache.ts:82"],
  },

  // ── The console's own required pair — services/console/lib/auth.ts, production only ───────
  {
    name: "CONSOLE_SESSION_SECRET",
    readers: ["console"],
    source: "installer",
    requiredFor: ["console"],
    fallback: null,
    secret: true,
    breaksWithout: "In production the console throws on the first request that needs a session; in any other mode it silently signs sessions with a fixed, publicly known secret.",
    readAt: ["services/console/lib/auth.ts:12", "services/console/lib/account-oauth-state.ts:18"],
  },
  {
    // W8C-s2b(b): a mounted file wins over the plain env value, through the console's own
    // readSecret (services/console/lib/secrets.ts) — but only where readSecret can safely be
    // used. lib/account-oauth-state.ts is Node-only and reads it that way. lib/auth.ts's
    // getSecret() does NOT: it is reachable from middleware.ts, which Next compiles for the
    // Edge Runtime, and readSecret's `node:fs` import fails that build outright (confirmed with
    // `next build --webpack`, see the comment on lib/auth.ts's getSecret()). So this file
    // currently changes only the OAuth `state` round-trip's secret, not the session cookie's —
    // an honest partial fix, not the whole of ruling (b).
    name: "CONSOLE_SESSION_SECRET_FILE",
    readers: ["console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The add-account OAuth `state` round-trip falls back to the plain CONSOLE_SESSION_SECRET value (or, if that is also unset, a fixed publicly known one outside production). The console's session cookie is unaffected either way — lib/auth.ts does not read this name.",
    readAt: ["services/console/lib/account-oauth-state.ts:18", "services/console/lib/secrets.ts:7"],
  },
  {
    name: "CONSOLE_ALLOWED_EMAILS",
    readers: ["console", "chief-of-staff", "creative"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "In production the console throws on login when no allow-list is configured. Outside production an empty allow-list admits nobody. Unmanaged web-chat approvals without an approver list are refused.",
    readAt: ["services/console/lib/auth.ts:152", "services/chief-of-staff/lib/principals.ts (ENV_VAR_FOR.console)", "services/creative/lib/principals.ts (ENV_VAR_FOR.console)"],
  },

  // ── The fixed 13 (plus the door files and platform secrets) every agent container gets ────
  {
    name: "HTTPS_PROXY",
    readers: ["chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Outbound HTTPS from this agent bypasses the sealed egress proxy and reaches vendors directly instead of through the allow-listed squid (ADR-0019).",
    readAt: ["services/keeper/lib/compose-agents.ts:69"],
  },
  {
    name: "HTTP_PROXY",
    readers: ["chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Outbound HTTP from this agent bypasses the sealed egress proxy and reaches vendors directly instead of through the allow-listed squid (ADR-0019).",
    readAt: ["services/keeper/lib/compose-agents.ts:69"],
  },
  {
    name: "SLACK_PROXY_URL",
    readers: ["chief-of-staff", "creative", "agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A Slack API call from this agent goes out directly instead of through the sealed egress proxy.",
    readAt: ["packages/agent-kit/src/slack-dispatcher.ts:78", "packages/agent-kit/src/telegram-fetch.ts:47"],
  },
  {
    name: "TELEGRAM_PROXY_URL",
    readers: ["travel", "agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A Telegram Bot API call from this agent goes out directly instead of through the sealed egress proxy.",
    readAt: ["packages/agent-kit/src/telegram-fetch.ts:46"],
  },
  {
    name: "EGRESS_PROXY_URL",
    readers: ["chief-of-staff", "agent-kit", "notion-sync", "atlas"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A read-it-later fetch, a Google token refresh or a Notion/calendar sync call goes out directly instead of through the sealed egress proxy.",
    readAt: ["packages/agent-kit/src/google-auth.ts:232", "services/chief-of-staff/lib/notion-page.ts:71", "services/atlas/bin/atlas-sync.ts:68"],
  },
  {
    name: "EVE_SCHEDULES_LIVE",
    readers: ["chief-of-staff", "travel", "creative", "agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: "0",
    secret: false,
    breaksWithout: "Every proactive schedule (reminders, digest, dream, trip-lifecycle) stays dark; this is the cutover switch and it fails closed on anything but the exact string \"1\".",
    readAt: ["packages/agent-kit/src/schedule-gate.ts:23"],
  },
  {
    name: "LARES_AGENT_INCARNATION",
    readers: ["chief-of-staff", "travel", "creative", "agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks when it is unset — it marks a MANAGED identity; unset, the agent falls back to its single-owner legacy identity path instead.",
    readAt: ["services/chief-of-staff/lib/principals.ts:41", "packages/agent-kit/src/door-authority.ts:8"],
  },
  {
    name: "LARES_RUNTIME_CONTROL_SECRET_FILE",
    readers: ["agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed incarnation's runtime-control route (conversation reset) cannot authenticate its caller.",
    readAt: ["packages/agent-kit/src/conversation-route.ts:7"],
  },
  {
    name: "AGENT_OWNER_USER_ID",
    readers: ["chief-of-staff", "travel", "console", "agent-kit"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Owner-scoped operations throw when the configured owner id is missing or blank; no installation identity is guessed.",
    readAt: ["services/chief-of-staff/lib/principals.ts:41", "packages/agent-kit/src/note-tools.ts:135"],
  },
  {
    name: "LARES_SLACK_PRINCIPAL",
    readers: ["chief-of-staff", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed incarnation's Slack allow-list resolves empty, so a Slack message from the real owner is refused as coming from nobody trusted.",
    readAt: ["services/chief-of-staff/lib/principals.ts:87"],
  },
  {
    name: "LARES_SLACK_CLAIM_REVISION",
    readers: ["chief-of-staff", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks directly — it records which door-claim revision this container was started with, for the keeper's own bookkeeping.",
    readAt: ["services/keeper/lib/compose-agents.ts:86"],
  },
  {
    name: "LARES_CONSOLE_PRINCIPAL",
    readers: ["chief-of-staff", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed incarnation's web-chat approver list resolves empty, so an approval answered from the console is refused as coming from nobody trusted — which is the behaviour before W8B-s5, and fail-closed. The keeper writes it from the owner address on a door or email claim; an installation with no claim at all has no console approver.",
    readAt: ["services/chief-of-staff/lib/principals.ts (templated LARES_${channel}_PRINCIPAL)", "services/keeper/lib/compose-agents.ts"],
  },
  {
    name: "LARES_TELEGRAM_PRINCIPAL",
    readers: ["travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed incarnation's Telegram allow-list resolves empty, so a message from the real owner is refused as coming from nobody trusted.",
    readAt: ["services/travel/lib/principals.ts:14"],
  },
  {
    name: "LARES_TELEGRAM_CLAIM_REVISION",
    readers: ["travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks directly — it records which door-claim revision this container was started with, for the keeper's own bookkeeping.",
    readAt: ["services/keeper/lib/compose-agents.ts:86"],
  },
  {
    name: "SLACK_ALLOWED_USER_IDS",
    readers: ["chief-of-staff", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Fail-closed: an unset or blank list admits nobody at all over Slack, including the real owner.",
    readAt: ["services/chief-of-staff/lib/principals.ts:78", "services/creative/lib/principals.ts:48"],
  },
  {
    name: "TELEGRAM_PRINCIPAL_ID",
    readers: ["chief-of-staff", "travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Fail-closed: an unset or blank value admits nobody at all over Telegram, including the real owner.",
    readAt: ["services/chief-of-staff/lib/principals.ts:79", "services/chief-of-staff/lib/principals.ts:182"],
  },
  {
    name: "MARCEL_ADMIN_TELEGRAM_ID",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The travel agent's Telegram admin commands and proactive DMs have nobody to address; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/agent/channels/telegram.ts:348", "services/travel/lib/principals.ts:14"],
  },
  {
    name: "GOOGLE_PRINCIPAL_ID",
    readers: ["chief-of-staff", "travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Google-backed tools (mail, calendar, drive) have no account key to look up stored OAuth tokens under.",
    readAt: ["services/chief-of-staff/lib/google.ts:840", "services/travel/lib/google.ts:226"],
  },
  {
    name: "LANGFUSE_PROXY_URL",
    readers: ["agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — tracing calls go out directly instead of through the sealed egress proxy when Langfuse is configured.",
    readAt: ["packages/agent-kit/src/langfuse-otel.ts:83"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. packages/agent-kit/src/langfuse-otel.ts:82.
    name: "LANGFUSE_HOST",
    readers: ["agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: "https://cloud.langfuse.com",
    secret: false,
    breaksWithout: "Nothing breaks — tracing goes to Langfuse Cloud's own default host instead of a self-hosted one.",
    readAt: ["packages/agent-kit/src/langfuse-otel.ts:82"],
  },

  // ── The four door-file keys (services/keeper/lib/compose-agents.ts's DOOR_FILES) ──────────
  {
    name: "SLACK_BOT_TOKEN_FILE",
    readers: ["chief-of-staff", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Slack door falls back to a bundled default token file that is never actually mounted, so every Slack call fails as unauthenticated.",
    readAt: ["services/chief-of-staff/agent/channels/slack.ts:69", "services/keeper/lib/compose-agents.ts:13"],
  },
  {
    name: "SLACK_SIGNING_SECRET_FILE",
    readers: ["chief-of-staff", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Inbound Slack webhook requests cannot be verified, so the door refuses every one of them.",
    readAt: ["services/chief-of-staff/agent/channels/slack.ts:70", "services/keeper/lib/compose-agents.ts:13"],
  },
  {
    name: "TELEGRAM_BOT_TOKEN_FILE",
    readers: ["chief-of-staff", "travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Telegram door falls back to a bundled default token file that is never actually mounted, so every Telegram call fails as unauthenticated.",
    readAt: ["services/travel/lib/telegram-credentials.ts:47", "services/keeper/lib/compose-agents.ts:14"],
  },
  {
    name: "TELEGRAM_WEBHOOK_SECRET_TOKEN_FILE",
    readers: ["chief-of-staff", "travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Inbound Telegram webhook requests cannot be verified, so the door refuses every one of them.",
    readAt: ["services/travel/lib/telegram-credentials.ts:48", "services/keeper/lib/compose-agents.ts:14"],
  },
  {
    name: "TELEGRAM_BOT_TOKEN",
    readers: ["travel"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "eve's own Telegram channel binding (not this repository's code) has no bot token to authenticate with.",
    readAt: ["services/travel/tests/sweep-marker.test.ts:54"],
  },
  {
    name: "TELEGRAM_BOT_USERNAME",
    readers: ["chief-of-staff", "travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A deep link or an @-mention the agent sends cannot name its own Telegram bot.",
    readAt: ["services/chief-of-staff/agent/channels/telegram.ts:84", "services/travel/agent/channels/telegram.ts:122"],
  },

  // ── Platform secrets — the engine's own, never an installation's integration list ─────────
  {
    name: "LANGFUSE_KEY_FILE",
    readers: ["agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — tracing is best-effort and warns once, but no turn is ever traced to Langfuse.",
    readAt: ["packages/agent-kit/src/langfuse-otel.ts:33"],
  },
  {
    name: "EVE_ROUTE_PASSWORD_FILE",
    readers: ["chief-of-staff", "travel", "creative", "console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The agent's own eve HTTP door refuses every request as unauthenticated (HTTP Basic has no password to check against); in the console, web chat answers \"No route password is mounted\" and reaches no agent.",
    readAt: [
      "services/chief-of-staff/agent/channels/eve.ts",
      "services/travel/agent/channels/eve.ts:31",
      "services/creative/agent/channels/eve.ts:31",
      "services/console/app/api/chat/[name]/[...path]/route.ts",
    ],
  },
  {
    name: "EVE_SAGA_ROUTE_PASSWORD_FILE",
    readers: ["chief-of-staff"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The chief-of-staff role's own eve HTTP door refuses every request as unauthenticated; a persona-named spelling wave 9 removes (it should be EVE_ROUTE_PASSWORD_FILE, matching every other role).",
    readAt: ["services/chief-of-staff/agent/channels/eve.ts:31"],
  },
  {
    name: "TOKEN_ENC_KEY_FILE",
    readers: ["agent-kit", "console", "notion-sync"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A stored Google OAuth refresh token cannot be decrypted (or newly encrypted), so a Google-backed tool fails the next time it needs to refresh.",
    readAt: ["packages/agent-kit/src/google-auth.ts:104", "services/console/lib/accounts.ts:121"],
  },
  {
    name: "TOKEN_ENC_KEY",
    readers: ["box", "console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The plain-value form of the same key: a stored OAuth token cannot be encrypted or decrypted, so the box refuses with a hex-length error.",
    readAt: ["services/box/lib/crypto.ts:32", "services/console/lib/accounts.ts:121"],
  },

  // ── The managed Google email flow (keeper-written) ────────────────────────────────────────
  {
    name: "LARES_EMAIL_PRINCIPAL",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed mailbox claim has no account key, so mail and calendar tools cannot look up its stored OAuth tokens.",
    readAt: ["services/chief-of-staff/lib/managed-google.ts:7"],
  },
  {
    name: "LARES_EMAIL_MAILBOX",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed mailbox claim has no address to read or send as.",
    readAt: ["services/chief-of-staff/lib/managed-google.ts:7"],
  },
  {
    name: "LARES_EMAIL_ORG",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed mailbox claim does not know which Google organisation's OAuth client to use.",
    readAt: ["services/chief-of-staff/lib/managed-google.ts:7", "services/chief-of-staff/lib/google-orgs.ts:76"],
  },
  {
    name: "LARES_EMAIL_CLAIM_REVISION",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks directly — it records which door-claim revision this container was started with, for the keeper's own bookkeeping.",
    readAt: ["services/chief-of-staff/lib/managed-google.ts:7", "services/keeper/lib/compose-agents.ts:110"],
  },
  {
    name: "GMAIL_PRIMARY_EMAIL",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Mail tools have no mailbox to act as; they refuse rather than guess.",
    readAt: ["services/chief-of-staff/lib/google.ts:795", "services/chief-of-staff/lib/google-drive.ts:43"],
  },
  {
    name: "CALENDAR_PRIMARY_EMAIL",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Calendar tools and the morning/evening briefs have no calendar to read.",
    readAt: ["services/chief-of-staff/lib/google.ts:809", "services/chief-of-staff/agent/schedules/email-triage.ts:271"],
  },
  {
    name: "LARES_GOOGLE_CLIENT_ID_FILE",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed incarnation's Google OAuth flow cannot start: it has a client secret but no client id.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:76"],
  },
  {
    name: "LARES_GOOGLE_CLIENT_SECRET_FILE",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A managed incarnation's Google OAuth flow cannot start: it has a client id but no client secret.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:76"],
  },

  // ── Keeper's bindable environmentKeys (services/keeper/lib/runtime-bindings.ts:10-17) ─────
  {
    name: "ATLAS_PATH",
    readers: ["chief-of-staff", "travel", "creative", "agent-kit", "atlas"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Every Atlas (shared business vault) tool throws StorePathNotConfiguredError on first use.",
    readAt: ["packages/agent-kit/src/notes-store.ts:22", "services/atlas/lib/config.ts:96"],
  },
  {
    name: "VAULT_PATH",
    readers: ["chief-of-staff", "travel", "creative", "agent-kit"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Every Brain (personal vault) tool throws StorePathNotConfiguredError on first use. Reached only through STORE_ENV, never a literal `process.env.VAULT_PATH` — see packages/agent-kit/src/notes-store.ts.",
    readAt: ["packages/agent-kit/src/notes-store.ts:21"],
  },
  {
    name: "MARCEL_DATA_ROOT",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nearly every travel tool and schedule has nowhere to read or write trip data; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/agent/instructions/trip-context.ts:50", "services/travel/lib/shared-budget.ts:28"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. services/travel/lib/shared-budget.ts:32.
    name: "MARCEL_BUDGET_FILE",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the shared token budget falls back to a file under MARCEL_DATA_ROOT instead of the owner's chosen path; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/lib/shared-budget.ts:32"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. services/travel/lib/shared-budget.ts:36.
    name: "MARCEL_DAILY_TOKEN_BUDGET",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: "2000000",
    secret: false,
    breaksWithout: "Nothing breaks — the shared token budget falls back to a built-in daily cap instead of the owner's chosen one; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/lib/shared-budget.ts:36"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. services/travel/lib/shared-budget.ts:47.
    name: "MARCEL_BUDGET_TZ",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: "Europe/Oslo",
    secret: false,
    breaksWithout: "Nothing breaks — the shared token budget's day boundary falls back to a fixed timezone instead of the owner's chosen one; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/lib/shared-budget.ts:47"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. services/travel/agent/schedules/trip-lifecycle.ts:64.
    name: "MARCEL_CONNECTION_BUFFER_MIN",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the international-leg connection-buffer check falls back to flightwatch.ts's own built-in threshold; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/agent/schedules/trip-lifecycle.ts:64"],
  },
  {
    name: "TASTE_ROOT",
    readers: ["travel", "console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Taste-learning tools (place preferences) have no store to read or write.",
    readAt: ["services/travel/lib/taste-store.ts:28", "services/console/lib/taste-store.ts:25"],
  },
  {
    name: "TRAVEL_PATH",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks loudly — a brief silently omits the travel role's itinerary context instead of including it.",
    readAt: ["services/chief-of-staff/lib/owner-clock.ts:141", "services/chief-of-staff/lib/travel-store.ts:53"],
  },
  {
    name: "NETWORK_DB_PATH",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: "/srv/network/network.db",
    secret: false,
    breaksWithout: "Nothing breaks — the network/contacts store falls back to a fixed default path, which is wrong on a container without that mount.",
    readAt: ["services/chief-of-staff/lib/network-client.ts:50"],
  },
  {
    name: "BRIEF_PICKS_DIR",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The morning brief's saved picks have no directory to read from or write to.",
    readAt: ["services/chief-of-staff/agent/schedules/morning-brief.ts:941"],
  },
  {
    name: "TZ",
    readers: ["chief-of-staff", "travel", "creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Consumed by the Node runtime's own timezone handling, not by this repository's code — unset, every Date/Intl call in the process uses the container image's default zone instead of the installation's.",
    readAt: ["services/keeper/lib/runtime-bindings.ts:12"],
  },
  {
    name: "OWNER_HOME_TZ",
    readers: ["chief-of-staff", "travel", "console"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The owner clock and proactivity windows fall back to the schedule's own fixed zone instead of the owner's actual one.",
    readAt: ["services/chief-of-staff/lib/owner-clock.ts:42", "services/console/lib/proactivity.ts:356"],
  },
  {
    name: "GIT_AUTHOR_NAME",
    readers: ["agent-kit", "keeper", "box"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Consumed by the `git` binary itself, not this repository's code — unset, a vault commit is attributed to whatever identity the container image happens to carry, or fails outright if none does.",
    readAt: ["services/keeper/lib/runtime-bindings.ts:12", "services/keeper/lib/git-backup.ts:32"],
  },
  {
    name: "GIT_AUTHOR_EMAIL",
    readers: ["agent-kit", "keeper", "box"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Consumed by the `git` binary itself: unset, a vault commit is attributed to whatever identity the container image happens to carry, or fails outright if none does.",
    readAt: ["services/keeper/lib/runtime-bindings.ts:12", "services/keeper/lib/git-backup.ts:32"],
  },
  {
    name: "GIT_COMMITTER_NAME",
    readers: ["agent-kit", "keeper", "box"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Consumed by the `git` binary itself: the commit's committer identity is whatever the container image happens to carry, or the commit fails outright if none does.",
    readAt: ["services/keeper/lib/runtime-bindings.ts:12", "services/keeper/lib/git-backup.ts:42"],
  },
  {
    name: "GIT_COMMITTER_EMAIL",
    readers: ["agent-kit", "keeper", "box"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Consumed by the `git` binary itself: the commit's committer identity is whatever the container image happens to carry, or the commit fails outright if none does.",
    readAt: ["services/keeper/lib/runtime-bindings.ts:12", "services/keeper/lib/git-backup.ts:42"],
  },
  {
    name: "STUDIO_MODEL",
    readers: ["creative"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the creative role falls further down its own model chain instead of using the installation's chosen studio model.",
    readAt: ["services/creative/lib/llm-complete.ts:35"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. services/creative/lib/llm-complete.ts:35,
    // services/creative/agent/agent.ts:79.
    name: "EVE_CALLIOPE_MODEL",
    readers: ["creative"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the creative role's model selection falls back to the agent's own definition model or the gateway's default instead of the env override; a persona-named spelling wave 9 removes.",
    readAt: ["services/creative/lib/llm-complete.ts:35", "services/creative/agent/agent.ts:79"],
  },
  {
    name: "MARCEL_MODEL_BRAIN",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — reflection/reasoning calls fall back to the gateway's own default model; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/agent/agent.ts:30", "services/travel/lib/distill.ts:17"],
  },
  {
    name: "MARCEL_MODEL_GATE",
    readers: ["travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the Telegram gate's classifier call falls back to the gateway's own default model; a persona-named spelling wave 9 removes.",
    readAt: ["services/travel/agent/channels/telegram.ts:300"],
  },
  {
    // Missed by W8A-s1; found by the W8A-s2 scan. services/chief-of-staff/agent/agent.ts:30.
    name: "EVE_SAGA_MODEL",
    readers: ["chief-of-staff"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the chief of staff's model selection falls back to the agent's own definition model instead of the env override; a persona-named spelling wave 9 removes.",
    readAt: ["services/chief-of-staff/agent/agent.ts:30"],
  },
  {
    name: "KARAKEEP_URL",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The digest's read-it-later save step has nowhere to send a link, and is skipped.",
    readAt: ["services/chief-of-staff/agent/schedules/digest.ts:131"],
  },
  {
    name: "SIGNAL_SPINE_URL",
    readers: ["chief-of-staff", "atlas", "notion-sync", "console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A cross-agent signal (e.g. a proactivity nudge) has nowhere to be posted, and is dropped.",
    readAt: ["services/chief-of-staff/lib/signal-emit.ts:133", "services/atlas/bin/atlas-sync.ts:48", "services/console/lib/signals.ts:18"],
  },
  {
    name: "SIGNAL_PROJECT",
    readers: ["chief-of-staff", "atlas", "notion-sync"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A cross-agent signal has no project scope to post under, and is dropped.",
    readAt: ["services/chief-of-staff/lib/signal-emit.ts:24", "services/atlas/lib/adapters/signal-notify.ts:16"],
  },
  {
    name: "EVE_DREAM_LIVE",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: "0",
    secret: false,
    breaksWithout: "The dream (learning) schedule stays dark even once EVE_SCHEDULES_LIVE is on; it fails closed on anything but the exact string \"1\".",
    readAt: ["services/chief-of-staff/agent/schedules/dream.ts:72"],
  },
  {
    name: "EVE_DIGEST_LIVE",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: "0",
    secret: false,
    breaksWithout: "The digest schedule stays dark even once EVE_SCHEDULES_LIVE is on; it fails closed on anything but the exact string \"1\".",
    readAt: ["services/chief-of-staff/agent/schedules/digest.ts:73"],
  },
  {
    name: "DIGEST_SLACK_TARGET",
    readers: ["chief-of-staff"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The digest falls back to the first allow-listed Slack user instead of a chosen target.",
    readAt: ["services/chief-of-staff/agent/schedules/digest.ts:110"],
  },
  {
    name: "GOOGLE_ORG",
    readers: ["travel"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The travel role's read-only Google adapter does not know which organisation's OAuth client to use.",
    readAt: ["services/travel/lib/google.ts:228"],
  },

  // ── Owner-tunable behaviour, no vendor at the other end ────────────────────────────────────
  {
    name: "BRIEF_CALENDAR_DENY",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: "birthday,bursdag,helligdag,holiday,tasks,oppgaver,trainerroad,week number,ukenummer",
    secret: false,
    breaksWithout: "Nothing breaks — the brief falls back to a built-in list of calendar-name patterns to exclude instead of the owner's own choices.",
    readAt: ["services/chief-of-staff/lib/calendar-fanout.ts:50"],
  },
  {
    name: "COMMERCIAL_BRANDS",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The commercial who-to-contact tool has no configured brand list to scope its search to.",
    readAt: ["services/chief-of-staff/agent/tools/commercial_who_to_contact.ts:39"],
  },
  {
    name: "COMMERCIAL_MODEL",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the commercial who-to-contact tool falls back to the gateway's own default model for its \"brain\" purpose.",
    readAt: ["services/chief-of-staff/agent/tools/commercial_who_to_contact.ts:82"],
  },
  {
    name: "COMMERCIAL_SWEEP_MAX",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: "200",
    secret: false,
    breaksWithout: "Nothing breaks — the commercial sweep falls back to a built-in cap on how many people it considers.",
    readAt: ["services/chief-of-staff/agent/tools/commercial_who_to_contact.ts:90"],
  },
  {
    name: "DREAM_MODEL",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the dream (learning) schedule falls back to the gateway's own default model for its \"brain\" purpose.",
    readAt: ["services/chief-of-staff/agent/schedules/dream.ts:185"],
  },
  {
    name: "ROUTE_MODEL",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — CRM routing falls back to the gateway's own default model for its classifier call.",
    readAt: ["services/chief-of-staff/agent/schedules/crm-routing.ts:309"],
  },
  {
    name: "EMBED_MODEL",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — voice-learning embeddings fall back to one installation's own embedding-model alias baked into the code.",
    readAt: ["services/chief-of-staff/agent/schedules/voice-learn.ts:146", "services/chief-of-staff/lib/voice-store.ts:96"],
  },
  {
    name: "OBLIGATION_TIMEOUT_MS",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: "20000",
    secret: false,
    breaksWithout: "Nothing breaks — an obligation (a promise the agent tracked) falls back to a built-in 20-second timeout instead of the owner's chosen one.",
    readAt: ["services/chief-of-staff/agent/schedules/reping.ts:50"],
  },
  {
    name: "OBLIGATION_REPING_ENABLED",
    readers: ["chief-of-staff"],
    source: "owner",
    requiredFor: [],
    fallback: "0",
    secret: false,
    breaksWithout: "Nothing breaks — the re-ping schedule runs and does nothing, by design, until this is explicitly turned on.",
    readAt: ["services/chief-of-staff/agent/schedules/reping.ts:83"],
  },
  {
    name: "LARES_PUBLIC_DOOR_ORIGIN",
    readers: ["console"],
    source: "owner",
    requiredFor: [],
    fallback: "",
    secret: false,
    breaksWithout: "Nothing breaks — the console's agent-settings screen shows no public origin for a door's webhook URL instead of the installation's real one.",
    readAt: ["services/console/lib/builder.ts:79"],
  },

  // ── Console-internal wiring ────────────────────────────────────────────────────────────────
  {
    name: "CONSOLE_OAUTH_REDIRECT",
    readers: ["console"],
    source: "owner",
    requiredFor: [],
    fallback: "http://localhost:3000/api/auth/callback",
    secret: false,
    breaksWithout: "Nothing breaks in development — sign-in falls back to a localhost redirect, which is wrong on any real installation and throws in production once GOOGLE_CLIENT_ID_CONSOLE is also missing.",
    readAt: ["services/console/middleware.ts:6", "services/console/app/api/auth/[...route]/route.ts:18"],
  },
  {
    name: "CONSOLE_PRINCIPAL_ID",
    readers: ["console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Uses AGENT_OWNER_USER_ID when unset; owner-scoped console operations throw if neither principal nor owner is configured.",
    readAt: ["services/console/lib/accounts.ts:22"],
  },
  {
    name: "LARES_KEEPER_SOCKET",
    readers: ["console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The console cannot reach the keeper at all: no definitions, no door claims, no conversation resets.",
    readAt: ["services/console/lib/keeper-client.ts:91"],
  },
  {
    name: "PORT",
    readers: ["chief-of-staff", "travel", "readability"],
    source: "installer",
    requiredFor: [],
    fallback: "8080",
    secret: false,
    breaksWithout: "Nothing breaks — the standalone webhook listener or the readability server falls back to a built-in port instead of the one the platform expects.",
    readAt: ["services/readability/bin/serve.ts:8", "services/chief-of-staff/agent/channels/telegram-webhook.ts:49"],
  },

  // ── Google integration (self-service OAuth, distinct from the managed email flow) ─────────
  {
    name: "GOOGLE_ORG_DOMAINS",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The console cannot resolve which configured Google organisation an email address belongs to.",
    readAt: ["services/console/lib/accounts.ts:70"],
  },
  {
    name: "GOOGLE_DEFAULT_ORG",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "An account-connect request with no domain match has no default organisation to fall back to.",
    readAt: ["services/console/app/api/accounts/google/start/route.ts:33"],
  },
  {
    name: "GOOGLE_REDIRECT_URI",
    readers: ["chief-of-staff", "notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: "",
    secret: false,
    breaksWithout: "A Google OAuth flow started by this reader has no callback URL to send Google back to.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:85", "services/notion-sync/lib/cli.ts:100"],
  },
  {
    name: "GOOGLE_PLACES_API_KEY",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The console's geocoder cannot resolve a place name to coordinates.",
    readAt: ["services/console/lib/geocode.ts:248"],
  },
  {
    name: "GOOGLE_PLACES_API_KEY_FILE",
    readers: ["console", "travel"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The console's geocoder, or the travel role's nearby-places tool, cannot resolve a place name to coordinates.",
    readAt: ["services/console/lib/geocode.ts:250", "services/travel/lib/sveip-run.ts:239"],
  },
  {
    name: "GOOGLE_CLIENT_ID_CONSOLE",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: "",
    secret: true,
    breaksWithout: "In production the console's own sign-in route throws; in development sign-in silently uses an empty client id and fails at Google instead.",
    readAt: ["services/console/app/api/auth/[...route]/route.ts:40"],
  },
  {
    name: "GOOGLE_CLIENT_SECRET_CONSOLE",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: "",
    secret: true,
    breaksWithout: "In production the console's own sign-in route throws; in development the OAuth token exchange silently uses an empty client secret and fails at Google instead.",
    readAt: ["services/console/app/api/auth/[...route]/route.ts:70"],
  },
  {
    name: "GOOGLE_CLIENT_ID_HEIBERG_FILE",
    readers: ["chief-of-staff", "travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "One installation's self-service Google OAuth client for that organisation cannot start; a fixed org-named spelling wave 9 removes in favour of a per-installation org registry.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:63", "services/travel/lib/google.ts:185"],
  },
  {
    name: "GOOGLE_CLIENT_SECRET_HEIBERG_FILE",
    readers: ["chief-of-staff", "travel"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "One installation's self-service Google OAuth client for that organisation cannot complete a token exchange; a fixed org-named spelling wave 9 removes.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:64", "services/travel/lib/google.ts:186"],
  },
  {
    name: "GOOGLE_CLIENT_ID_ZERO7_FILE",
    readers: ["chief-of-staff"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "One installation's self-service Google OAuth client for a second organisation cannot start; a fixed org-named spelling wave 9 removes.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:67"],
  },
  {
    name: "GOOGLE_CLIENT_SECRET_ZERO7_FILE",
    readers: ["chief-of-staff"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "One installation's self-service Google OAuth client for a second organisation cannot complete a token exchange; a fixed org-named spelling wave 9 removes.",
    readAt: ["services/chief-of-staff/lib/google-orgs.ts:68"],
  },

  // ── Notion integration ──────────────────────────────────────────────────────────────────────
  {
    name: "NOTION_TOKEN",
    readers: ["chief-of-staff", "notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "A Notion-backed tool or the sync job cannot authenticate to the Notion API at all.",
    readAt: ["services/chief-of-staff/lib/notion-page.ts:62", "services/notion-sync/lib/cli.ts:361"],
  },
  {
    name: "NOTION_TOKEN_FILE",
    readers: ["chief-of-staff", "notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A Notion-backed tool or the sync job cannot authenticate to the Notion API at all.",
    readAt: ["services/chief-of-staff/lib/notion-page.ts:60", "services/chief-of-staff/agent/schedules/meeting-followup.ts:697"],
  },
  {
    name: "NOTION_MEETINGS_DATA_SOURCE_ID",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The meeting-followup schedule has no Notion database to file meeting notes into, and skips.",
    readAt: ["services/chief-of-staff/agent/schedules/meeting-followup.ts:691"],
  },
  {
    name: "NOTION_SYNC_CONFIG",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Notion sync job has no page/database mapping to run, and has nothing to do.",
    readAt: ["services/notion-sync/lib/config.ts:386"],
  },
  {
    name: "NOTION_SYNC_LIVE",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Notion sync job's own live gate stays closed and it refuses to write anything.",
    readAt: ["services/notion-sync/bin/notion-sync.ts:82"],
  },
  {
    name: "NOTION_SYNC_DRY_RUN",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the sync job runs for real instead of only reporting what it would change.",
    readAt: ["services/notion-sync/bin/notion-sync.ts:100"],
  },
  {
    name: "NOTION_SYNC_TOLERANCE_MINUTES",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the sync job falls back to its own built-in clock-skew tolerance between the two sides.",
    readAt: ["services/notion-sync/bin/notion-sync.ts:103"],
  },
  {
    name: "NOTION_SYNC_TICK_MS",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the sync job's own poll loop falls back to its built-in interval.",
    readAt: ["services/notion-sync/bin/notion-sync.ts:108"],
  },
  {
    name: "NOTION_SYNC_PRINCIPAL",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The sync job throws on startup: it has no owner identity to attribute its writes to.",
    readAt: ["services/notion-sync/lib/cli.ts:368"],
  },

  // ── Twenty CRM integration ──────────────────────────────────────────────────────────────────
  {
    name: "TWENTY_BASE_URL",
    readers: ["chief-of-staff", "notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Twenty CRM client has no base URL to call; the sync job's CLI throws on startup.",
    readAt: ["services/chief-of-staff/lib/twenty-client.ts:66", "services/notion-sync/lib/cli.ts:977"],
  },
  {
    name: "TWENTY_KEY_FILE",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Twenty CRM client cannot authenticate to the CRM's API.",
    readAt: ["services/chief-of-staff/lib/twenty-client.ts:54"],
  },
  {
    name: "TWENTY_KEY",
    readers: ["notion-sync"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The sync job's Twenty CRM client cannot authenticate to the CRM's API.",
    readAt: ["services/notion-sync/lib/cli.ts:978"],
  },
  {
    name: "TWENTY_REQUEST_TIMEOUT_MS",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the Twenty CRM client falls back to its own built-in request timeout.",
    readAt: ["services/chief-of-staff/lib/twenty-client.ts:46"],
  },

  // ── Karakeep integration (read-it-later) ───────────────────────────────────────────────────
  {
    name: "KARAKEEP_API_KEY_FILE",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The digest's read-it-later save step cannot authenticate, and is skipped.",
    readAt: ["services/chief-of-staff/agent/schedules/digest.ts:135"],
  },

  // ── Orakel integration (company enrichment) ────────────────────────────────────────────────
  {
    name: "ORAKEL_URL",
    readers: ["chief-of-staff", "travel", "creative", "agent-kit"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Company-enrichment tools and the commercial who-to-contact tool have no Orakel endpoint to call, and report as unconfigured rather than failing loudly.",
    readAt: ["services/chief-of-staff/lib/orakel-client.ts:40", "packages/agent-kit/extension/extension.ts"],
  },
  {
    name: "ORAKEL_KEY_FILE",
    readers: ["chief-of-staff", "travel", "creative", "agent-kit"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Company-enrichment tools cannot authenticate to Orakel's API.",
    readAt: ["services/chief-of-staff/lib/orakel-client.ts:42"],
  },

  // ── Readability integration (read-it-later article extraction) ────────────────────────────
  {
    name: "READABILITY_TOKEN",
    readers: ["agent-kit", "readability"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The readability server refuses to start (\"READABILITY_TOKEN[_FILE] required\"); a caller's article-extraction tool cannot authenticate to it.",
    readAt: ["services/readability/bin/serve.ts:5", "packages/agent-kit/src/readability-client.ts:86"],
  },
  {
    name: "READABILITY_TOKEN_FILE",
    readers: ["agent-kit", "readability"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The readability server refuses to start (\"READABILITY_TOKEN[_FILE] required\"); a caller's article-extraction tool cannot authenticate to it.",
    readAt: ["services/readability/bin/serve.ts:6", "packages/agent-kit/src/readability-client.ts:86"],
  },
  {
    name: "READABILITY_URL",
    readers: ["agent-kit"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "An article-extraction tool has no readability server to call, and reports as unconfigured rather than failing loudly.",
    readAt: ["packages/agent-kit/src/readability-client.ts:98"],
  },

  // ── Signal integration (the fleet's own cross-agent notification bus) ─────────────────────
  {
    name: "SIGNAL_SPINE_TOKEN",
    readers: ["chief-of-staff", "notion-sync", "atlas"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "A cross-agent signal cannot authenticate to the signal spine, and is dropped.",
    readAt: ["services/chief-of-staff/lib/signal-emit.ts:60", "services/atlas/lib/config.ts:78"],
  },
  {
    name: "SIGNAL_SPINE_TOKEN_FILE",
    readers: ["chief-of-staff", "notion-sync", "atlas"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A cross-agent signal cannot authenticate to the signal spine, and is dropped.",
    readAt: ["services/chief-of-staff/lib/signal-emit.ts:44", "services/atlas/lib/config.ts:64"],
  },
  {
    name: "SIGNAL_READ_TOKEN",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The console cannot read signals back from the spine to show in its own UI.",
    readAt: ["services/console/lib/signals.ts:69"],
  },
  {
    name: "SIGNAL_READ_TOKEN_FILE",
    readers: ["chief-of-staff", "console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "A tool or the console that reads signals back from the spine cannot authenticate to do so.",
    readAt: ["services/chief-of-staff/agent/schedules/morning-brief.ts:1001", "services/console/lib/signals.ts:69"],
  },
  {
    name: "SIGNAL_ADMIN_TOKEN",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The console's signal admin screens (rules, catalogue, consumers) cannot authenticate to the spine.",
    readAt: ["services/console/lib/signals.ts:83"],
  },

  // ── CRM status webhook (console-side) ──────────────────────────────────────────────────────
  {
    name: "CRM_STATUS_URL",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The console's CRM status panel has no endpoint to call, and shows nothing.",
    readAt: ["services/console/lib/crm-status.ts:163"],
  },
  {
    name: "CRM_STATUS_TOKEN",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The console's CRM status panel cannot authenticate to the CRM's webhook.",
    readAt: ["services/console/lib/crm-status.ts:166"],
  },
  {
    name: "CRM_STATUS_TOKEN_FILE",
    readers: ["console"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The console's CRM status panel cannot authenticate to the CRM's webhook.",
    readAt: ["services/console/lib/crm-status.ts:166"],
  },

  // ── Slack integration tunables (not part of the fixed door-claim wiring above) ─────────────
  {
    name: "SLACK_MAX_CONVERSATIONS",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the morning brief's Slack scan falls back to its own built-in cap on how many conversations it scans.",
    readAt: ["services/chief-of-staff/agent/schedules/morning-brief.ts:233"],
  },
  {
    name: "SLACK_SCAN_TIMEOUT_MS",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the morning brief's Slack scan falls back to its own built-in timeout.",
    readAt: ["services/chief-of-staff/agent/schedules/morning-brief.ts:206"],
  },
  {
    name: "SLACK_TOKEN_PRINCIPAL_ID",
    readers: ["chief-of-staff"],
    source: "integration",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Slack user-token lookup requires this value or an explicit principal argument and refuses before querying credentials when neither is configured.",
    readAt: ["services/chief-of-staff/lib/slack-source.ts:57"],
  },

  // ── Atlas sync job ──────────────────────────────────────────────────────────────────────────
  {
    name: "BRAIN_PATH",
    readers: ["atlas"],
    source: "installer",
    requiredFor: [],
    fallback: "/srv/brain",
    secret: false,
    breaksWithout: "Nothing breaks — the Atlas reader falls back to a fixed default path, which is wrong on a container without that mount.",
    readAt: ["services/atlas/lib/config.ts:97"],
  },
  {
    name: "ATLAS_SYNC_TICK_MS",
    readers: ["atlas"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "Nothing breaks — the Atlas sync job's poll loop falls back to its own built-in interval.",
    readAt: ["services/atlas/lib/config.ts:86"],
  },
  {
    name: "ATLAS_SYNC_LIVE",
    readers: ["atlas"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The Atlas sync job's own live gate stays closed and it refuses to write anything.",
    readAt: ["services/atlas/lib/config.ts:108"],
  },

  // ── Probe/dev-only knobs — never set on an installation ────────────────────────────────────
  {
    name: "EVE_GATE_PROOF_LOG",
    readers: ["chief-of-staff"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: NOT_AN_INSTALLATION_SETTING,
    readAt: ["services/chief-of-staff/catalogue/echo_note.ts:36"],
  },
  {
    name: "DREAM_RUN_NOW",
    readers: ["chief-of-staff"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: NOT_AN_INSTALLATION_SETTING,
    readAt: ["services/chief-of-staff/agent/schedules/dream.ts:282"],
  },
  {
    name: "NODE_ENV",
    readers: ["console"],
    source: "legacy",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: NOT_AN_INSTALLATION_SETTING + " The console's own Dockerfile always sets it to \"production\"; that is what makes CONSOLE_SESSION_SECRET and CONSOLE_ALLOWED_EMAILS hard failures on the real image.",
    readAt: ["services/console/lib/auth.ts:13", "services/console/lib/auth.ts:153"],
  },

  // ── PG* — read directly by box and console, distinct from DATABASE_URL/WORKFLOW_POSTGRES_URL ─
  {
    name: "PGHOST",
    readers: ["box", "console"],
    source: "installer",
    requiredFor: [],
    fallback: "db",
    secret: false,
    breaksWithout: "Nothing breaks — the connection falls back to a built-in default host, which is wrong outside the reference compose network.",
    readAt: ["services/box/lib/db.ts:28", "services/console/lib/db.ts:11"],
  },
  {
    name: "PGPORT",
    readers: ["box", "console"],
    source: "installer",
    requiredFor: [],
    fallback: "5432",
    secret: false,
    breaksWithout: "Nothing breaks — the connection falls back to Postgres's own default port.",
    readAt: ["services/box/lib/db.ts:29", "services/console/lib/db.ts:12"],
  },
  {
    name: "PGDATABASE",
    readers: ["box", "console"],
    source: "installer",
    requiredFor: [],
    fallback: "lares_state",
    secret: false,
    breaksWithout: "Nothing breaks — the connection falls back to a built-in default database name, which may not be the one this installation actually uses.",
    readAt: ["services/box/lib/db.ts:30", "services/console/lib/db.ts:13"],
  },
  {
    name: "PGUSER",
    readers: ["box", "console"],
    source: "installer",
    requiredFor: [],
    fallback: "lares",
    secret: false,
    breaksWithout: "Nothing breaks — the connection falls back to a built-in default user, which may not exist on this installation's database.",
    readAt: ["services/box/lib/db.ts:31", "services/console/lib/db.ts:14"],
  },
  {
    name: "PGPASSWORD",
    readers: ["box", "console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: true,
    breaksWithout: "The connection is attempted with no password, which Postgres refuses unless trust auth is configured (never the case on a real installation).",
    readAt: ["services/box/lib/db.ts:20", "services/console/lib/db.ts:5"],
  },
  {
    name: "PGPASSWORD_FILE",
    readers: ["console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The console falls back to the plain PGPASSWORD value instead of the mounted secret file.",
    readAt: ["services/console/lib/db.ts:6"],
  },

  // ── The engine's own telemetry off-switch (Dockerfile ENV, no TypeScript reader) ───────────
  {
    name: "EVE_TELEMETRY_DISABLED",
    readers: ["chief-of-staff", "travel", "creative", "console"],
    source: "installer",
    requiredFor: [],
    fallback: "1",
    secret: false,
    breaksWithout: "Consumed by the eve framework itself, not this repository's code — every engine image hardcodes it to \"1\" in its Dockerfile (`pnpm -C packages/agent-kit exec vitest run tests/no-telemetry.test.ts` pins this), so it can only go missing if a build strips it, and usage would then be reported to eve's telemetry endpoint.",
    readAt: ["services/chief-of-staff/Dockerfile:28", "packages/agent-kit/tests/no-telemetry.test.ts:26"],
  },

  // ── The neutral stack's own containers — the model gateway and the edge proxy (8F) ────────
  {
    name: "LARES_CONFIGURED_MODEL_ALIAS",
    readers: ["console"],
    source: "installer",
    requiredFor: [],
    fallback: null,
    secret: false,
    breaksWithout: "The agent builder offers every purpose alias from models.alias_prefix, including aliases an on-box single-model gateway does not serve. Older externally managed gateways may intentionally leave it unset.",
    readAt: ["services/console/lib/builder.ts"],
  },
  {
    name: "MODEL_PROVIDER_KEY_FILE",
    readers: ["gateway"],
    source: "installer",
    requiredFor: ["gateway"],
    fallback: null,
    secret: false,
    breaksWithout: "The gateway container's own startup guard refuses to start at all, before any request is served.",
    readAt: ["images/gateway-runtime/start.sh"],
  },
  {
    name: "GATEWAY_MASTER_KEY_FILE",
    readers: ["gateway"],
    source: "installer",
    requiredFor: ["gateway"],
    fallback: null,
    secret: false,
    breaksWithout: "The gateway container's own startup guard refuses to start at all, before any request is served.",
    readAt: ["images/gateway-runtime/start.sh"],
  },
  {
    name: "LARES_DOMAIN",
    readers: ["caddy"],
    source: "owner",
    requiredFor: ["caddy"],
    fallback: null,
    secret: false,
    breaksWithout: "Caddy has no domain to request a certificate for or route requests on, and cannot front the console at all.",
    readAt: ["services/box/ops/Caddyfile", "services/box/ops/install.sh"],
  },
];

export function settingsFor(reader: SettingReader): readonly SettingDef[] {
  return SETTINGS.filter((s) => s.readers.includes(reader));
}

export function settingByName(name: string): SettingDef | undefined {
  return SETTINGS.find((s) => s.name === name);
}

/** The names a reader cannot start without, in declaration order. */
export function requiredNamesFor(reader: SettingReader): readonly string[] {
  return SETTINGS.filter((s) => s.requiredFor.includes(reader)).map((s) => s.name);
}

export const SETTING_NAMES: ReadonlySet<string> = new Set(SETTINGS.map((s) => s.name));
